export const OBTER_PROJETOS = "OBTER_PROJETOS"
export const CADASTRAR_PROJETOS = "CADASTRAR_PROJETOS"
export const ALTERAR_PROJETOS = "ALTERAR_PROJETOS"
export const REMOVE_PROJETO = "REMOVE_PROJETO"

export const OBTER_TAREFAS = "OBTER_TAREFAS"
export const DEFINIR_TAREFAS = "DEFINIR_TAREFAS"
export const CADASTRAR_TAREFA = "CADASTRAR_TAREFA"
export const ALTERAR_TAREFA = "ALTERAR_TAREFA"
export const DELETAR_TAREFA = 'DELETAR_TAREFA';
